/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStakePoolRewardMultiplier,
  IStakePoolRewardMultiplierInterface,
} from "../IStakePoolRewardMultiplier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_end",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_from",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_to",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_rewardPerSecond",
        type: "uint256",
      },
    ],
    name: "getRewardMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IStakePoolRewardMultiplier__factory {
  static readonly abi = _abi;
  static createInterface(): IStakePoolRewardMultiplierInterface {
    return new utils.Interface(_abi) as IStakePoolRewardMultiplierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakePoolRewardMultiplier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IStakePoolRewardMultiplier;
  }
}
